global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  gravity:
    type: cosmos
    value:
      key: gravity_relay_account
      chain-id: gravity-local-1
      rpc-addr: tcp://0.0.0.0:26657/
      account-prefix: gravity
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.025stake
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  stargaze:
    type: cosmos
    value:
      key: stargaze_relay_account
      chain-id: stargaze-local-1
      rpc-addr: tcp://0.0.0.0:36657/
      account-prefix: stars
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.025stake
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
paths:
  gravity-stargaze:
    src:
      chain-id: stargaze-local-1
    dst:
      chain-id: gravity-local-1
    src-channel-filter:
      rule: ""
      channel-list: []
